language: python
branches:
  only:
    - master

arch: amd64
os: linux
sudo: required

python:
- '3.7'
- '3.8'
- '3.9'


before_install:
  - sudo chown travis /usr/local/bin
  - pip install --upgrade pip
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc

install:
  - pip install -r requirements.txt
  - pip install -e .
  - op --version

script: pytest

deploy:
  provider: pypi
  user: dtprycewandera
  password:
    secure: JHFShd8I2MWZRLTkjOksK6bUdkdi2+FYKPO1ZmzrycsWfzD2vTYnqYylqsFHagRv7KkyWhUnRttm94xx7C6cWMRPytlCOaYXGR0TB7QO5ajif5PjnVre0O8dWzdIuBofrxB2otZ3K8RpUgcj27frxFCqQxvBtKPsNLwN0UTXD2mGRevHdcCvZVfHdXw0cbW9umeLNJmnlzVug6O3xDY8BF0cdVOhciHElcGij1YSOfZLwz0Ru5AfiFkf/3DdqDq8IiWysKViUgbuW4Tre51sI8KIGhB5Nle2QWKWOdyFGvQk2UXWGjXwmybzwStFAvpMbyJV0RsCAUFYJrH1LQbn9s1ZZ+W8KqJwGjnkCpeinz12a/61JKhV/Igz+ZSTVlkKW8/Y0skQ/U7BjnO/PWbjCw15vJ8TCtgrOFpw+yxyFqogTOWlPfwL7ox5gbC/AHRMzSDkWEl2aYRCnPsWpavjvuKRnSWKKbmv8fiIBZ5et6a3ftw1uAO3O2OwRmnobAhDglRChHbbxtjq94Nns9YeCaN+t+uMqM7oWaDfsiM0CEC0thXdzGDqvv4KJWA0IetSg7afX9DYzy3YntEmCZFhIRGgGhhk1DtYNT75+cnwde0nzNO2bmpgKYn6c4OpjUNxz86ijlReDzSJiCDtJWtKxLRnuu3E8PyxuAOFZs4x8nk=
  on:
    branch: master

after_deploy:
  - git checkout master
  - python -c "from onepassword.utils import bump_version; bump_version()"
  - git add .
  - git commit -m "[skip travis] Bumping version on master"
  - git push
